default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['DATABASE_USERNAME'] || 'postgres' %>
  password: <%= ENV['DATABASE_PASSWORD'] || 'postgres' %>
  host: db

development:
  <<: *default
  database: inss_discount_development

test:
  <<: *default
  database: inss_discount_test

production:
  <<: *default
  database: inss_discount_production
